/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Express Inventory API
 * API documentation for the Express Inventory System
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { axiosInstance } from '../../../lib/axios';




export const test = (

 signal?: AbortSignal
) => {


      return axiosInstance<string>(
      {url: `/test`, method: 'GET', signal
    },
      );
    }




export const getTestQueryKey = () => {
    return [
    `/test`
    ] as const;
    }


export const getTestQueryOptions = <TData = Awaited<ReturnType<typeof test>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof test>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTestQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof test>>> = ({ signal }) => test(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof test>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TestQueryResult = NonNullable<Awaited<ReturnType<typeof test>>>
export type TestQueryError = unknown


export function useTest<TData = Awaited<ReturnType<typeof test>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof test>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof test>>,
          TError,
          Awaited<ReturnType<typeof test>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTest<TData = Awaited<ReturnType<typeof test>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof test>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof test>>,
          TError,
          Awaited<ReturnType<typeof test>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTest<TData = Awaited<ReturnType<typeof test>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof test>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTest<TData = Awaited<ReturnType<typeof test>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof test>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTestQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






