/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Express Inventory API
 * API documentation for the Express Inventory System
 * OpenAPI spec version: 1.0.0
 */
export interface UpdateUserRequest {
  firstName?: string;
  lastName?: string;
}

export type UserDTORole = typeof UserDTORole[keyof typeof UserDTORole];


export const UserDTORole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
  STOCK_COUNTER: 'STOCK_COUNTER',
} as const;

export interface UserDTO {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  role: UserDTORole;
}

export interface FieldError {
  field?: string;
  message?: string;
}

export interface ApiResponseUserDTO {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: UserDTO;
  fieldErrors?: FieldError[];
}

export type CreateUserRequestRole = typeof CreateUserRequestRole[keyof typeof CreateUserRequestRole];


export const CreateUserRequestRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
  STOCK_COUNTER: 'STOCK_COUNTER',
} as const;

export interface CreateUserRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  role: CreateUserRequestRole;
}

export interface CreateProductRequest {
  name: string;
  category: string;
  stock: number;
  lowStockThreshold: number;
  price: number;
}

export interface Product {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  name?: string;
  category?: string;
  stock?: number;
  lowStockThreshold?: number;
  price?: number;
}

export interface ApiResponseProduct {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: Product;
  fieldErrors?: FieldError[];
}

export interface ApiResponseListProduct {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: Product[];
  fieldErrors?: FieldError[];
}

export interface LoginRequest {
  email?: string;
  password: string;
}

export interface PurchaseEntity {
  purchaseId?: number;
  productId?: number;
  userId?: number;
  orderStatus?: string;
  orderPrice?: number;
  purchaseDate?: string;
  quantity?: number;
}

export interface UpdateProductRequest {
  id?: number;
  name?: string;
  productType?: string;
  stock?: number;
  stockThreshold?: number;
  price?: number;
}

export interface ApiResponseListUserDTO {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: UserDTO[];
  fieldErrors?: FieldError[];
}

export interface UserSearchRequest {
  email?: string;
  name?: string;
}

export interface ProductSummaryResponse {
  totalProducts?: number;
  totalStock?: number;
  totalUnitPrice?: number;
  totalInventoryValue?: number;
}

export interface ApiResponseProductSummaryResponse {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ProductSummaryResponse;
  fieldErrors?: FieldError[];
}

export interface ProductResponse {
  id?: number;
  name?: string;
  category?: string;
  price?: number;
  stock?: number;
  lowStockThreshold?: number;
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  paged?: boolean;
  sort?: SortObject;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
}

export interface PageProductResponse {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: ProductResponse[];
  number?: number;
  first?: boolean;
  last?: boolean;
  sort?: SortObject;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}

export interface ApiResponsePageProductResponse {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: PageProductResponse;
  fieldErrors?: FieldError[];
}

export type GetFilteredRequestStockStatus = typeof GetFilteredRequestStockStatus[keyof typeof GetFilteredRequestStockStatus];


export const GetFilteredRequestStockStatus = {
  NO_STOCK: 'NO_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  ABOVE_THRESHOLD: 'ABOVE_THRESHOLD',
} as const;

export interface GetFilteredRequest {
  category?: string;
  stockStatus?: GetFilteredRequestStockStatus;
}

export interface NotificationDTO {
  id?: number;
  message?: string;
  type?: string;
  isRead?: boolean;
}

export interface ApiResponseListNotificationDTO {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: NotificationDTO[];
  fieldErrors?: FieldError[];
}

export type InventoryTransactionActionType = typeof InventoryTransactionActionType[keyof typeof InventoryTransactionActionType];


export const InventoryTransactionActionType = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  UPDATE: 'UPDATE',
} as const;

export interface InventoryTransaction {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  product?: Product;
  stockChange?: number;
  actionType?: InventoryTransactionActionType;
  note?: string;
}

export type ApiResponseObjectData = { [key: string]: unknown };

export interface ApiResponseObject {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ApiResponseObjectData;
  fieldErrors?: FieldError[];
}

export type ApiResponseVoidData = { [key: string]: unknown };

export interface ApiResponseVoid {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ApiResponseVoidData;
  fieldErrors?: FieldError[];
}

export type CreateProductsWithCsvBody = {
  file: Blob;
};

export type SearchUsersParams = {
request: UserSearchRequest;
};

export type SearchProductParams = {
keyword: string;
};

export type GetAllProducts1Params = {
page?: number;
size?: number;
};

export type FilterProductsParams = {
request: GetFilteredRequest;
};

