/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface CreateProductRequest {
  name: string;
  category: string;
  stock: number;
  lowStockThreshold: number;
  price: number;
}

export interface ProductEntity {
  id?: number;
  name?: string;
  category?: string;
  stock?: number;
  lowStockThreshold?: number;
  price?: number;
  createdAt?: string;
  lastUpdated?: string;
}

export interface FieldError {
  field?: string;
  message?: string;
}

export interface ApiResponseProductEntity {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ProductEntity;
  fieldErrors?: FieldError[];
}

export interface ApiResponseListProductEntity {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ProductEntity[];
  fieldErrors?: FieldError[];
}

export interface PurchaseEntity {
  purchaseId?: number;
  productId?: number;
  userId?: number;
  orderStatus?: string;
  orderPrice?: number;
  purchaseDate?: string;
  quantity?: number;
}

export interface UpdateProductRequest {
  id?: number;
  name?: string;
  productType?: string;
  stock?: number;
  stockThreshold?: number;
  price?: number;
}

export interface ProductSummaryResponse {
  totalProducts?: number;
  totalStock?: number;
  totalUnitPrice?: number;
  totalInventoryValue?: number;
}

export interface ApiResponseProductSummaryResponse {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ProductSummaryResponse;
  fieldErrors?: FieldError[];
}

export interface ProductResponse {
  id?: number;
  name?: string;
  category?: string;
  price?: number;
  stock?: number;
  lowStockThreshold?: number;
}

export interface SortObject {
  empty?: boolean;
  unsorted?: boolean;
  sorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  unpaged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  sort?: SortObject;
  paged?: boolean;
}

export interface PageProductResponse {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: ProductResponse[];
  number?: number;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  pageable?: PageableObject;
  sort?: SortObject;
  empty?: boolean;
}

export interface ApiResponsePageProductResponse {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: PageProductResponse;
  fieldErrors?: FieldError[];
}

export type GetFilteredRequestStockStatus = typeof GetFilteredRequestStockStatus[keyof typeof GetFilteredRequestStockStatus];


export const GetFilteredRequestStockStatus = {
  NO_STOCK: 'NO_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  ABOVE_THRESHOLD: 'ABOVE_THRESHOLD',
} as const;

export interface GetFilteredRequest {
  category?: string;
  stockStatus?: GetFilteredRequestStockStatus;
}

export type InventoryLogEntityActionType = typeof InventoryLogEntityActionType[keyof typeof InventoryLogEntityActionType];


export const InventoryLogEntityActionType = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  UPDATE: 'UPDATE',
} as const;

export type InventoryLogEntityCreatedAtSignerCertPathCertificatesItemPublicKeyParams = { [key: string]: unknown };

export type InventoryLogEntityCreatedAtSignerCertPathCertificatesItemPublicKey = {
  params?: InventoryLogEntityCreatedAtSignerCertPathCertificatesItemPublicKeyParams;
  encoded?: string;
  format?: string;
  algorithm?: string;
};

export type InventoryLogEntityCreatedAtSignerCertPathCertificatesItem = {
  type?: string;
  encoded?: string;
  publicKey?: InventoryLogEntityCreatedAtSignerCertPathCertificatesItemPublicKey;
};

export type InventoryLogEntityCreatedAtSignerCertPathEncodings = { [key: string]: unknown };

export type InventoryLogEntityCreatedAtSignerCertPath = {
  certificates?: InventoryLogEntityCreatedAtSignerCertPathCertificatesItem[];
  type?: string;
  encoded?: string;
  encodings?: InventoryLogEntityCreatedAtSignerCertPathEncodings;
};

export type InventoryLogEntityCreatedAt = {
  timestamp?: string;
  signerCertPath?: InventoryLogEntityCreatedAtSignerCertPath;
};

export interface InventoryLogEntity {
  logId?: number;
  product?: ProductEntity;
  stockChange?: number;
  actionType?: InventoryLogEntityActionType;
  note?: string;
  changedAt?: string;
  createdAt?: InventoryLogEntityCreatedAt;
}

export type ApiResponseVoidData = { [key: string]: unknown };

export interface ApiResponseVoid {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ApiResponseVoidData;
  fieldErrors?: FieldError[];
}

export type CreateProductsWithCsvBody = {
  file: Blob;
};

export type SearchProductParams = {
keyword: string;
};

export type GetAllProducts1Params = {
page?: number;
size?: number;
};

export type FilterProductsParams = {
request: GetFilteredRequest;
};

