/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Express Inventory API
 * API documentation for the Express Inventory System
 * OpenAPI spec version: 1.0.0
 */
export interface UpdateUserRequest {
  firstName?: string;
  lastName?: string;
}

export type UserDTORole = typeof UserDTORole[keyof typeof UserDTORole];


export const UserDTORole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
  STOCK_COUNTER: 'STOCK_COUNTER',
} as const;

export interface UserDTO {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  role: UserDTORole;
}

export interface FieldError {
  field?: string;
  message?: string;
}

export interface ApiResponseUserDTO {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: UserDTO;
  fieldErrors?: FieldError[];
}

export type CreateUserRequestRole = typeof CreateUserRequestRole[keyof typeof CreateUserRequestRole];


export const CreateUserRequestRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
  STOCK_COUNTER: 'STOCK_COUNTER',
} as const;

export interface CreateUserRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  role: CreateUserRequestRole;
}

export interface CreateProductRequest {
  name: string;
  category: string;
  stock: number;
  lowStockThreshold: number;
  price: number;
}

export interface ProductResponse {
  id: number;
  name: string;
  category: string;
  price: number;
  stock: number;
  lowStockThreshold: number;
}

export interface ApiResponseProductResponse {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ProductResponse;
  fieldErrors?: FieldError[];
}

export type ProductCategory = typeof ProductCategory[keyof typeof ProductCategory];


export const ProductCategory = {
  PRODUCE: 'PRODUCE',
  PLASTIC: 'PLASTIC',
} as const;

export interface Product {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  name?: string;
  category?: ProductCategory;
  stock?: number;
  lowStockThreshold?: number;
  price?: number;
}

export interface ApiResponseListProduct {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: Product[];
  fieldErrors?: FieldError[];
}

export interface LoginRequest {
  email?: string;
  password: string;
}

export interface PurchaseOrderRecordDTO {
  productId: number;
  quantity: number;
  unitPrice: number;
}

export interface CreatePurchaseOrderRequest {
  orderStatus: string;
  orderPrice: number;
  totalQuantity: number;
  records: PurchaseOrderRecordDTO[];
}

export interface PurchaseOrderRecord {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  purchaseOrder?: PurchaseOrder;
  product?: Product;
  quantity?: number;
  unitPrice?: number;
}

export interface PurchaseOrder {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  records?: PurchaseOrderRecord[];
  userId?: number;
  orderStatus?: string;
  orderPrice?: number;
  totalQuantity?: number;
}

export interface UpdateProductRequest {
  id?: number;
  name?: string;
  productType?: string;
  stock?: number;
  stockThreshold?: number;
  price?: number;
}

export interface ApiResponseProduct {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: Product;
  fieldErrors?: FieldError[];
}

export type UpdateStockRequestActionType = typeof UpdateStockRequestActionType[keyof typeof UpdateStockRequestActionType];


export const UpdateStockRequestActionType = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  UPDATE: 'UPDATE',
} as const;

export interface UpdateStockRequest {
  stockChange: number;
  actionType: UpdateStockRequestActionType;
  note: string;
}

export type ApiResponseVoidData = { [key: string]: unknown };

export interface ApiResponseVoid {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ApiResponseVoidData;
  fieldErrors?: FieldError[];
}

export interface ApiResponseListUserDTO {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: UserDTO[];
  fieldErrors?: FieldError[];
}

export interface UserSearchRequest {
  email?: string;
  name?: string;
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  paged?: boolean;
  unpaged?: boolean;
  pageNumber?: number;
  pageSize?: number;
}

export interface PageProductResponse {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: ProductResponse[];
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
}

export interface ApiResponsePageProductResponse {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: PageProductResponse;
  fieldErrors?: FieldError[];
}

export interface ProductSummaryResponse {
  totalProducts: number;
  totalStock: number;
  totalUnitPrice: number;
  totalInventoryValue: number;
}

export interface ApiResponseProductSummaryResponse {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ProductSummaryResponse;
  fieldErrors?: FieldError[];
}

export interface NotificationDTO {
  id: number;
  message: string;
  type: string;
  isRead: boolean;
}

export interface ApiResponseListNotificationDTO {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: NotificationDTO[];
  fieldErrors?: FieldError[];
}

export type InventoryTransactionActionType = typeof InventoryTransactionActionType[keyof typeof InventoryTransactionActionType];


export const InventoryTransactionActionType = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  UPDATE: 'UPDATE',
} as const;

export interface InventoryTransaction {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  product?: Product;
  stockChange?: number;
  actionType?: InventoryTransactionActionType;
  note?: string;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export type AuditLogAction = typeof AuditLogAction[keyof typeof AuditLogAction];


export const AuditLogAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  EXPORT: 'EXPORT',
  BULK_CREATE: 'BULK_CREATE',
  BULK_DELETE: 'BULK_DELETE',
} as const;

export type AuditLogOldValue = {[key: string]: { [key: string]: unknown }};

export type AuditLogNewValue = {[key: string]: { [key: string]: unknown }};

export interface AuditLog {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  userId?: number;
  action?: AuditLogAction;
  entity?: string;
  entityId?: string;
  oldValue?: AuditLogOldValue;
  newValue?: AuditLogNewValue;
}

export interface PageAuditLog {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: AuditLog[];
  number?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
}

export interface ApiResponsePageAuditLog {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: PageAuditLog;
  fieldErrors?: FieldError[];
}

export type ApiResponseObjectData = { [key: string]: unknown };

export interface ApiResponseObject {
  timestamp?: string;
  status?: number;
  success?: boolean;
  error?: string;
  message?: string;
  path?: string;
  data?: ApiResponseObjectData;
  fieldErrors?: FieldError[];
}

export type GetAllProductsParams = {
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
search?: string;
category?: GetAllProductsCategory;
stockStatus?: GetAllProductsStockStatus;
};

export type GetAllProductsCategory = typeof GetAllProductsCategory[keyof typeof GetAllProductsCategory];


export const GetAllProductsCategory = {
  PRODUCE: 'PRODUCE',
  PLASTIC: 'PLASTIC',
} as const;

export type GetAllProductsStockStatus = typeof GetAllProductsStockStatus[keyof typeof GetAllProductsStockStatus];


export const GetAllProductsStockStatus = {
  NO_STOCK: 'NO_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  ABOVE_THRESHOLD: 'ABOVE_THRESHOLD',
} as const;

export type CreateProductsWithCsvBody = {
  file: Blob;
};

export type SearchUsersParams = {
request: UserSearchRequest;
};

export type GetProductSummaryParams = {
search?: string;
category?: GetProductSummaryCategory;
stockStatus?: GetProductSummaryStockStatus;
};

export type GetProductSummaryCategory = typeof GetProductSummaryCategory[keyof typeof GetProductSummaryCategory];


export const GetProductSummaryCategory = {
  PRODUCE: 'PRODUCE',
  PLASTIC: 'PLASTIC',
} as const;

export type GetProductSummaryStockStatus = typeof GetProductSummaryStockStatus[keyof typeof GetProductSummaryStockStatus];


export const GetProductSummaryStockStatus = {
  NO_STOCK: 'NO_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  ABOVE_THRESHOLD: 'ABOVE_THRESHOLD',
} as const;

export type GetAuditLogsParams = {
pageable: Pageable;
};

