/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InventoryLogEntity
} from '../types.schemas';

import { axiosInstance } from '../../../lib/axios';




export const getAllLogs = (

 signal?: AbortSignal
) => {


      return axiosInstance<InventoryLogEntity[]>(
      {url: `/api/v1/logs`, method: 'GET', signal
    },
      );
    }




export const getGetAllLogsQueryKey = () => {
    return [
    `/api/v1/logs`
    ] as const;
    }


export const getGetAllLogsQueryOptions = <TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLogsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLogs>>> = ({ signal }) => getAllLogs(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLogs>>>
export type GetAllLogsQueryError = unknown


export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLogs>>,
          TError,
          Awaited<ReturnType<typeof getAllLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLogs>>,
          TError,
          Awaited<ReturnType<typeof getAllLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllLogsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






