/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Express Inventory API
 * API documentation for the Express Inventory System
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PurchaseEntity
} from '../types.schemas';

import { axiosInstance } from '../../../lib/axios';




export const getPurchaseOrders = (

 signal?: AbortSignal
) => {


      return axiosInstance<PurchaseEntity[]>(
      {url: `/api/purchases`, method: 'GET', signal
    },
      );
    }




export const getGetPurchaseOrdersQueryKey = () => {
    return [
    `/api/purchases`
    ] as const;
    }


export const getGetPurchaseOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getPurchaseOrders>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPurchaseOrdersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPurchaseOrders>>> = ({ signal }) => getPurchaseOrders(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPurchaseOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getPurchaseOrders>>>
export type GetPurchaseOrdersQueryError = unknown


export function useGetPurchaseOrders<TData = Awaited<ReturnType<typeof getPurchaseOrders>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchaseOrders>>,
          TError,
          Awaited<ReturnType<typeof getPurchaseOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchaseOrders<TData = Awaited<ReturnType<typeof getPurchaseOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchaseOrders>>,
          TError,
          Awaited<ReturnType<typeof getPurchaseOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchaseOrders<TData = Awaited<ReturnType<typeof getPurchaseOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPurchaseOrders<TData = Awaited<ReturnType<typeof getPurchaseOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPurchaseOrdersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createPurchaseOrder = (
    purchaseEntity: PurchaseEntity,
 signal?: AbortSignal
) => {


      return axiosInstance<PurchaseEntity>(
      {url: `/api/purchases`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: purchaseEntity, signal
    },
      );
    }



export const getCreatePurchaseOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPurchaseOrder>>, TError,{data: PurchaseEntity}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPurchaseOrder>>, TError,{data: PurchaseEntity}, TContext> => {

const mutationKey = ['createPurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPurchaseOrder>>, {data: PurchaseEntity}> = (props) => {
          const {data} = props ?? {};

          return  createPurchaseOrder(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createPurchaseOrder>>>
    export type CreatePurchaseOrderMutationBody = PurchaseEntity
    export type CreatePurchaseOrderMutationError = unknown

    export const useCreatePurchaseOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPurchaseOrder>>, TError,{data: PurchaseEntity}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPurchaseOrder>>,
        TError,
        {data: PurchaseEntity},
        TContext
      > => {
      return useMutation(getCreatePurchaseOrderMutationOptions(options), queryClient);
    }
    export const getPurchaseOrder = (
    id: number,
 signal?: AbortSignal
) => {


      return axiosInstance<PurchaseEntity>(
      {url: `/api/purchases/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetPurchaseOrderQueryKey = (id: number,) => {
    return [
    `/api/purchases/${id}`
    ] as const;
    }


export const getGetPurchaseOrderQueryOptions = <TData = Awaited<ReturnType<typeof getPurchaseOrder>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPurchaseOrderQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPurchaseOrder>>> = ({ signal }) => getPurchaseOrder(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPurchaseOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getPurchaseOrder>>>
export type GetPurchaseOrderQueryError = unknown


export function useGetPurchaseOrder<TData = Awaited<ReturnType<typeof getPurchaseOrder>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchaseOrder>>,
          TError,
          Awaited<ReturnType<typeof getPurchaseOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchaseOrder<TData = Awaited<ReturnType<typeof getPurchaseOrder>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchaseOrder>>,
          TError,
          Awaited<ReturnType<typeof getPurchaseOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchaseOrder<TData = Awaited<ReturnType<typeof getPurchaseOrder>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPurchaseOrder<TData = Awaited<ReturnType<typeof getPurchaseOrder>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPurchaseOrderQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const deletePurchaseOrder = (
    id: number,
 signal?: AbortSignal
) => {


      return axiosInstance<void>(
      {url: `/api/purchases/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeletePurchaseOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePurchaseOrder>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePurchaseOrder>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePurchaseOrder>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePurchaseOrder(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof deletePurchaseOrder>>>

    export type DeletePurchaseOrderMutationError = unknown

    export const useDeletePurchaseOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePurchaseOrder>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePurchaseOrder>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeletePurchaseOrderMutationOptions(options), queryClient);
    }
