/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Express Inventory API
 * API documentation for the Express Inventory System
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageAuditLog,
  GetAuditLogsParams
} from '../types.schemas';

import { axiosInstance } from '../../../lib/axios';




export const getAuditLogs = (
    params: GetAuditLogsParams,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponsePageAuditLog>(
      {url: `/api/v1/audit`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetAuditLogsQueryKey = (params?: GetAuditLogsParams,) => {
    return [
    `/api/v1/audit`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuditLogsQueryOptions = <TData = Awaited<ReturnType<typeof getAuditLogs>>, TError = unknown>(params: GetAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuditLogsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuditLogs>>> = ({ signal }) => getAuditLogs(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuditLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getAuditLogs>>>
export type GetAuditLogsQueryError = unknown


export function useGetAuditLogs<TData = Awaited<ReturnType<typeof getAuditLogs>>, TError = unknown>(
 params: GetAuditLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getAuditLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuditLogs<TData = Awaited<ReturnType<typeof getAuditLogs>>, TError = unknown>(
 params: GetAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getAuditLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuditLogs<TData = Awaited<ReturnType<typeof getAuditLogs>>, TError = unknown>(
 params: GetAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAuditLogs<TData = Awaited<ReturnType<typeof getAuditLogs>>, TError = unknown>(
 params: GetAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuditLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






