/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Express Inventory API
 * API documentation for the Express Inventory System
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseListProduct,
  ApiResponsePageProductResponse,
  ApiResponseProduct,
  ApiResponseProductSummaryResponse,
  ApiResponseVoid,
  CreateProductRequest,
  CreateProductsWithCsvBody,
  FilterProductsParams,
  GetAllProducts1Params,
  SearchProductParams,
  UpdateProductRequest
} from '../types.schemas';

import { axiosInstance } from '../../../lib/axios';




export const getAllProducts = (

 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseListProduct>(
      {url: `/api/v1/products`, method: 'GET', signal
    },
      );
    }




export const getGetAllProductsQueryKey = () => {
    return [
    `/api/v1/products`
    ] as const;
    }


export const getGetAllProductsQueryOptions = <TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllProductsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProducts>>> = ({ signal }) => getAllProducts(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProducts>>>
export type GetAllProductsQueryError = unknown


export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createProduct = (
    createProductRequest: CreateProductRequest,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseProduct>(
      {url: `/api/v1/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProductRequest, signal
    },
      );
    }



export const getCreateProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: CreateProductRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: CreateProductRequest}, TContext> => {

const mutationKey = ['createProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProduct>>, {data: CreateProductRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProduct(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>
    export type CreateProductMutationBody = CreateProductRequest
    export type CreateProductMutationError = unknown

    export const useCreateProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: CreateProductRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProduct>>,
        TError,
        {data: CreateProductRequest},
        TContext
      > => {
      return useMutation(getCreateProductMutationOptions(options), queryClient);
    }
    export const createProductsWithCsv = (
    createProductsWithCsvBody: CreateProductsWithCsvBody,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseListProduct>(
      {url: `/api/v1/products/csv`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProductsWithCsvBody, signal
    },
      );
    }



export const getCreateProductsWithCsvMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductsWithCsv>>, TError,{data: CreateProductsWithCsvBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProductsWithCsv>>, TError,{data: CreateProductsWithCsvBody}, TContext> => {

const mutationKey = ['createProductsWithCsv'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProductsWithCsv>>, {data: CreateProductsWithCsvBody}> = (props) => {
          const {data} = props ?? {};

          return  createProductsWithCsv(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProductsWithCsvMutationResult = NonNullable<Awaited<ReturnType<typeof createProductsWithCsv>>>
    export type CreateProductsWithCsvMutationBody = CreateProductsWithCsvBody
    export type CreateProductsWithCsvMutationError = unknown

    export const useCreateProductsWithCsv = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductsWithCsv>>, TError,{data: CreateProductsWithCsvBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProductsWithCsv>>,
        TError,
        {data: CreateProductsWithCsvBody},
        TContext
      > => {
      return useMutation(getCreateProductsWithCsvMutationOptions(options), queryClient);
    }
    export const getProductById = (
    id: number,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseProduct>(
      {url: `/api/v1/products/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetProductByIdQueryKey = (id: number,) => {
    return [
    `/api/v1/products/${id}`
    ] as const;
    }


export const getGetProductByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductById>>> = ({ signal }) => getProductById(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>
export type GetProductByIdQueryError = unknown


export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const deleteProduct = (
    id: number,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseVoid>(
      {url: `/api/v1/products/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteProduct(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>

    export type DeleteProductMutationError = unknown

    export const useDeleteProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteProductMutationOptions(options), queryClient);
    }
    export const updateProduct = (
    id: number,
    updateProductRequest: UpdateProductRequest,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseProduct>(
      {url: `/api/v1/products/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProductRequest, signal
    },
      );
    }



export const getUpdateProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: UpdateProductRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: UpdateProductRequest}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {id: number;data: UpdateProductRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProduct(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = UpdateProductRequest
    export type UpdateProductMutationError = unknown

    export const useUpdateProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: UpdateProductRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {id: number;data: UpdateProductRequest},
        TContext
      > => {
      return useMutation(getUpdateProductMutationOptions(options), queryClient);
    }
    export const getProductSummary = (

 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseProductSummaryResponse>(
      {url: `/api/v1/products/summary`, method: 'GET', signal
    },
      );
    }




export const getGetProductSummaryQueryKey = () => {
    return [
    `/api/v1/products/summary`
    ] as const;
    }


export const getGetProductSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getProductSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductSummary>>> = ({ signal }) => getProductSummary(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getProductSummary>>>
export type GetProductSummaryQueryError = unknown


export function useGetProductSummary<TData = Awaited<ReturnType<typeof getProductSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductSummary>>,
          TError,
          Awaited<ReturnType<typeof getProductSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductSummary<TData = Awaited<ReturnType<typeof getProductSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductSummary>>,
          TError,
          Awaited<ReturnType<typeof getProductSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductSummary<TData = Awaited<ReturnType<typeof getProductSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductSummary<TData = Awaited<ReturnType<typeof getProductSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const searchProduct = (
    params: SearchProductParams,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseListProduct>(
      {url: `/api/v1/products/search`, method: 'GET',
        params, signal
    },
      );
    }




export const getSearchProductQueryKey = (params?: SearchProductParams,) => {
    return [
    `/api/v1/products/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchProductQueryOptions = <TData = Awaited<ReturnType<typeof searchProduct>>, TError = unknown>(params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchProductQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProduct>>> = ({ signal }) => searchProduct(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchProductQueryResult = NonNullable<Awaited<ReturnType<typeof searchProduct>>>
export type SearchProductQueryError = unknown


export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = unknown>(
 params: SearchProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = unknown>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = unknown>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = unknown>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getRecentlyAddedProducts = (

 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseListProduct>(
      {url: `/api/v1/products/recently_added_products`, method: 'GET', signal
    },
      );
    }




export const getGetRecentlyAddedProductsQueryKey = () => {
    return [
    `/api/v1/products/recently_added_products`
    ] as const;
    }


export const getGetRecentlyAddedProductsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentlyAddedProductsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentlyAddedProducts>>> = ({ signal }) => getRecentlyAddedProducts(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecentlyAddedProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentlyAddedProducts>>>
export type GetRecentlyAddedProductsQueryError = unknown


export function useGetRecentlyAddedProducts<TData = Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentlyAddedProducts>>,
          TError,
          Awaited<ReturnType<typeof getRecentlyAddedProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentlyAddedProducts<TData = Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentlyAddedProducts>>,
          TError,
          Awaited<ReturnType<typeof getRecentlyAddedProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentlyAddedProducts<TData = Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRecentlyAddedProducts<TData = Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentlyAddedProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecentlyAddedProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAllProducts1 = (
    params?: GetAllProducts1Params,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponsePageProductResponse>(
      {url: `/api/v1/products/pagination`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetAllProducts1QueryKey = (params?: GetAllProducts1Params,) => {
    return [
    `/api/v1/products/pagination`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllProducts1QueryOptions = <TData = Awaited<ReturnType<typeof getAllProducts1>>, TError = unknown>(params?: GetAllProducts1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllProducts1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProducts1>>> = ({ signal }) => getAllProducts1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProducts1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProducts1QueryResult = NonNullable<Awaited<ReturnType<typeof getAllProducts1>>>
export type GetAllProducts1QueryError = unknown


export function useGetAllProducts1<TData = Awaited<ReturnType<typeof getAllProducts1>>, TError = unknown>(
 params: undefined |  GetAllProducts1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts1>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts1<TData = Awaited<ReturnType<typeof getAllProducts1>>, TError = unknown>(
 params?: GetAllProducts1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts1>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts1<TData = Awaited<ReturnType<typeof getAllProducts1>>, TError = unknown>(
 params?: GetAllProducts1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllProducts1<TData = Awaited<ReturnType<typeof getAllProducts1>>, TError = unknown>(
 params?: GetAllProducts1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProducts1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const filterProducts = (
    params: FilterProductsParams,
 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseListProduct>(
      {url: `/api/v1/products/filter`, method: 'GET',
        params, signal
    },
      );
    }




export const getFilterProductsQueryKey = (params?: FilterProductsParams,) => {
    return [
    `/api/v1/products/filter`, ...(params ? [params] : [])
    ] as const;
    }


export const getFilterProductsQueryOptions = <TData = Awaited<ReturnType<typeof filterProducts>>, TError = unknown>(params: FilterProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filterProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilterProductsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filterProducts>>> = ({ signal }) => filterProducts(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filterProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilterProductsQueryResult = NonNullable<Awaited<ReturnType<typeof filterProducts>>>
export type FilterProductsQueryError = unknown


export function useFilterProducts<TData = Awaited<ReturnType<typeof filterProducts>>, TError = unknown>(
 params: FilterProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filterProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filterProducts>>,
          TError,
          Awaited<ReturnType<typeof filterProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilterProducts<TData = Awaited<ReturnType<typeof filterProducts>>, TError = unknown>(
 params: FilterProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filterProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filterProducts>>,
          TError,
          Awaited<ReturnType<typeof filterProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilterProducts<TData = Awaited<ReturnType<typeof filterProducts>>, TError = unknown>(
 params: FilterProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filterProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilterProducts<TData = Awaited<ReturnType<typeof filterProducts>>, TError = unknown>(
 params: FilterProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filterProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilterProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAllCategories = (

 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseListProduct>(
      {url: `/api/v1/products/every_category_name`, method: 'GET', signal
    },
      );
    }




export const getGetAllCategoriesQueryKey = () => {
    return [
    `/api/v1/products/every_category_name`
    ] as const;
    }


export const getGetAllCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getAllCategories>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCategoriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCategories>>> = ({ signal }) => getAllCategories(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCategories>>>
export type GetAllCategoriesQueryError = unknown


export function useGetAllCategories<TData = Awaited<ReturnType<typeof getAllCategories>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCategories<TData = Awaited<ReturnType<typeof getAllCategories>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCategories<TData = Awaited<ReturnType<typeof getAllCategories>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllCategories<TData = Awaited<ReturnType<typeof getAllCategories>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllCategoriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const deleteAllproducts = (

 signal?: AbortSignal
) => {


      return axiosInstance<ApiResponseVoid>(
      {url: `/api/v1/products/DELETE_EVERY_SINGLE_PRODUCT`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteAllproductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllproducts>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllproducts>>, TError,void, TContext> => {

const mutationKey = ['deleteAllproducts'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllproducts>>, void> = () => {


          return  deleteAllproducts()
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllproductsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllproducts>>>

    export type DeleteAllproductsMutationError = unknown

    export const useDeleteAllproducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllproducts>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllproducts>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteAllproductsMutationOptions(options), queryClient);
    }
