name: Full Stack Init Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    # Ensures the frontend can run
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install & Build Frontend
        working-directory: ./client
        run: |
          npm install
          npm run build

    # Ensures the backend can run
  backend-init:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: inventory_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Spring Boot Context Check
        working-directory: ./server
        env:
          DB_URL: jdbc:postgresql://localhost:5432/inventory_db
          DB_USERNAME: user
          DB_PASSWORD: password
          JWT_SECRET_KEY: de880e64fcda88375eb3647d376c3659ae33a1d0dd9358764cbbe889dd2c4b2d
        run: |
          chmod +x mvnw
          ./mvnw test