/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Express Inventory API
 * API documentation for the Express Inventory System
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTicketRequest,
  TicketResponse,
  UpdateTicketStatusRequest
} from '../types.schemas';

import { axiosInstance } from '../../../lib/axios';




export const getAllTickets = (

 signal?: AbortSignal
) => {


      return axiosInstance<TicketResponse[]>(
      {url: `/tickets`, method: 'GET', signal
    },
      );
    }




export const getGetAllTicketsQueryKey = () => {
    return [
    `/tickets`
    ] as const;
    }


export const getGetAllTicketsQueryOptions = <TData = Awaited<ReturnType<typeof getAllTickets>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTickets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTicketsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTickets>>> = ({ signal }) => getAllTickets(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTickets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllTicketsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTickets>>>
export type GetAllTicketsQueryError = unknown


export function useGetAllTickets<TData = Awaited<ReturnType<typeof getAllTickets>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTickets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTickets>>,
          TError,
          Awaited<ReturnType<typeof getAllTickets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTickets<TData = Awaited<ReturnType<typeof getAllTickets>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTickets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTickets>>,
          TError,
          Awaited<ReturnType<typeof getAllTickets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTickets<TData = Awaited<ReturnType<typeof getAllTickets>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTickets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllTickets<TData = Awaited<ReturnType<typeof getAllTickets>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTickets>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllTicketsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createTicket = (
    createTicketRequest: CreateTicketRequest,
 signal?: AbortSignal
) => {


      return axiosInstance<TicketResponse>(
      {url: `/tickets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTicketRequest, signal
    },
      );
    }



export const getCreateTicketMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTicket>>, TError,{data: CreateTicketRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTicket>>, TError,{data: CreateTicketRequest}, TContext> => {

const mutationKey = ['createTicket'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTicket>>, {data: CreateTicketRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTicket(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTicketMutationResult = NonNullable<Awaited<ReturnType<typeof createTicket>>>
    export type CreateTicketMutationBody = CreateTicketRequest
    export type CreateTicketMutationError = unknown

    export const useCreateTicket = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTicket>>, TError,{data: CreateTicketRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTicket>>,
        TError,
        {data: CreateTicketRequest},
        TContext
      > => {
      return useMutation(getCreateTicketMutationOptions(options), queryClient);
    }
    export const updateTicketStatus = (
    id: number,
    updateTicketStatusRequest: UpdateTicketStatusRequest,
 signal?: AbortSignal
) => {


      return axiosInstance<TicketResponse>(
      {url: `/tickets/${id}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTicketStatusRequest, signal
    },
      );
    }



export const getUpdateTicketStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTicketStatus>>, TError,{id: number;data: UpdateTicketStatusRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTicketStatus>>, TError,{id: number;data: UpdateTicketStatusRequest}, TContext> => {

const mutationKey = ['updateTicketStatus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTicketStatus>>, {id: number;data: UpdateTicketStatusRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTicketStatus(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTicketStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateTicketStatus>>>
    export type UpdateTicketStatusMutationBody = UpdateTicketStatusRequest
    export type UpdateTicketStatusMutationError = unknown

    export const useUpdateTicketStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTicketStatus>>, TError,{id: number;data: UpdateTicketStatusRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTicketStatus>>,
        TError,
        {id: number;data: UpdateTicketStatusRequest},
        TContext
      > => {
      return useMutation(getUpdateTicketStatusMutationOptions(options), queryClient);
    }
    export const getTicketById = (
    id: number,
 signal?: AbortSignal
) => {


      return axiosInstance<TicketResponse>(
      {url: `/tickets/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetTicketByIdQueryKey = (id: number,) => {
    return [
    `/tickets/${id}`
    ] as const;
    }


export const getGetTicketByIdQueryOptions = <TData = Awaited<ReturnType<typeof getTicketById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTicketById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTicketByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTicketById>>> = ({ signal }) => getTicketById(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTicketById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTicketByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTicketById>>>
export type GetTicketByIdQueryError = unknown


export function useGetTicketById<TData = Awaited<ReturnType<typeof getTicketById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTicketById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTicketById>>,
          TError,
          Awaited<ReturnType<typeof getTicketById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTicketById<TData = Awaited<ReturnType<typeof getTicketById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTicketById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTicketById>>,
          TError,
          Awaited<ReturnType<typeof getTicketById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTicketById<TData = Awaited<ReturnType<typeof getTicketById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTicketById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTicketById<TData = Awaited<ReturnType<typeof getTicketById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTicketById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTicketByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const deleteTicket = (
    id: number,
 signal?: AbortSignal
) => {


      return axiosInstance<void>(
      {url: `/tickets/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteTicketMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTicket>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTicket>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteTicket'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTicket>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteTicket(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTicketMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTicket>>>

    export type DeleteTicketMutationError = unknown

    export const useDeleteTicket = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTicket>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTicket>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteTicketMutationOptions(options), queryClient);
    }
